### ISSUE TITLE
About Error while Running SVM file in python

### ISSUE THREAD

**Issue by Tabassumrg** [kartik-joshi/Stock-predection#1]
Traceback (most recent call last):
  File "C:/Users/Broadway/PycharmProjects/pp1.py/SVM.py", line 48, in <module>
    testdataset =Read_file('APPL.csv')
  File "C:/Users/Broadway/PycharmProjects/pp1.py/SVM.py", line 9, in Read_file
    with open(file_name, 'r', newline='',encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'APPL.csv'

Process finished with exit code 1

**how to solve this Error

**Comment by kartik-joshi** [comment]
I have uploaded APPL.csv along with the code on the repo. That file contains data of Apple stock price. Make sure you have downloaded all the files and not deleted any file by mistake. You can also download the latest stock price from Yahoo Finance to get the updated results.
